services:
  web:
    build: .
    ports:
      - "8080:8080"
  files:
    build: ./files
    ports:
      - "8081:8080"
  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
